# Generated by Django 5.0.7 on 2024-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
